### ISSUE TITLE
How to correctly MoveCursor

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [GerardSmit/GhostCursor#1]
Sorry for my ignorace but how can I move mouse to xy cords? I see that IBrowser have 'MoveCursorToAsync' method, but looks like it uses PuppeterSharp stock implementation, moreover i'm not sure how should i wrap browser.

**Comment by GerardSmit** [comment]
No problem! You're correct that the IBrowser-implementation just calls the PuppeteerSharp method. I'm using IBrowser to redirect the calls to the specific library (e.g. PuppeteerSharp, Selenium or CefSharp).

There wasn't really a way to move the cursor with the ICursor interface. So I've added the following methods to ICursor:

```cs
interface ICursor
{
    /// <summary>
    /// Click the cursor at the current position.
    /// </summary>
    /// <param name="token">The cancellation token.</param>
    /// <returns>Returns a task that completes when the click is complete.</returns>
    Task ClickAsync(CancellationToken token = default);

    /// <summary>
    /// Clicks the cursor at the specified coordinates.
    /// </summary>
    /// <param name="x">The x-coordinate.</param>
    /// <param name="y">The y-coordinate.</param>
    /// <param name="token">The cancellation token.</param>
    /// <returns>Returns a task that completes when the click is complete.</returns>
    Task ClickAsync(int x, int y, CancellationToken token = default);

    /// <summary>
    /// Moves the cursor to the coordinates.
    /// </summary>
    /// <param name="x">The x-coordinate.</param>
    /// <param name="y">The y-coordinate.</param>
    /// <param name="steps">The number of steps to move the cursor.</param>
    /// <param name="moveSpeed">The speed to move the cursor.</param>
    /// <param name="token">The cancellation token.</param>
    /// <returns>Returns a task that completes when the move is complete.</returns>
    Task MoveToAsync(int x, int y, int? steps = null, TimeSpan? moveSpeed = null, CancellationToken token = default);
}
```

If you download the latest NuGet package ([GhostCursor.PuppeteerSharp](https://www.nuget.org/packages/GhostCursor.PuppeteerSharp/)) you should be able to use these methods.

**Comment by CaCTuCaTu4ECKuu** [comment]
Thanks, that should've help, but looks like I'm doing something wrong
![image](https://github.com/GerardSmit/GhostCursor/assets/8963134/390f91cc-f8dd-46f2-86ed-ac242c642e22)

I have everything that mentioned in readme, but when trying to click by selector or now by xy cords there's null reference.

I'm was thinking about forking repo and do a little work on it but decided to ask in case you can spare some time and do it faser than me. 
This code looks like there must be demand for it and i wonder that it's only PuppeterSharp cursor extension and was made pretty recently. Thank you a lot, I was about to despair of having to write it myself

**Comment by GerardSmit** [comment]
I can't reproduce this problem. What's the full stack trace of the exception?

<details>
  <summary>Test code</summary>
  
I've tried to reproduce this problem by running the following in [RoslynPad](https://roslynpad.net/):

```cs
#r "nuget: GhostCursor.PuppeteerSharp, 0.1.0"

using System.Threading.Tasks;
using GhostCursor;
using GhostCursor.PuppeteerSharp;
using PuppeteerSharp;

// Initialize PuppeteerSharp
using var browserFetcher = new BrowserFetcher();
await browserFetcher.DownloadAsync();
await using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = false
});

await using var page = await browser.NewPageAsync();
await page.GoToAsync("about:blank");

// Create the cursor
var options = new CursorOptions
{
    Debug = true,
    DefaultSteps = 20
};

var cursor = page.CreateCursor(options);

// Click at 100, 100
await using (await cursor.StartAsync())
{
    await cursor.ClickAsync(100, 100);
}

// Wait for 2 seconds before closing the browser
await Task.Delay(2000);
```
  
</details>

Maybe the page is null when you call `.CreateCursor()`?

**Comment by CaCTuCaTu4ECKuu** [comment]
You're right, I was creating cursor on browser initialization on empty page, but seems it's a no-no.
Thanks for help, I appreciate it
